### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Dash400air** [Dash400air/Paper-Introduction-JAIST2022#5]
## このプロジェクトの改善点を思いついた方はここにコメントして下さい

良いと思ったコメントは絵文字等で反応してくれると幸いです

**Comment by Dash400air** [comment]
読み終えた論文はcloseではなくopenにしたほうがいいかも

**Comment by kan25d5** [comment]
論文のPDFをCodeに公開するのは法的もしくはコンプライアンス的にまずいかも

**Comment by Dash400air** [comment]
**Discussionへ移行**
